---
title: "Fiddler Crabs and Bergmann’s Rule"
subtitle: "Explanatory Plots with Fiddler Crab Carapace Widths observed at the Different Lattitude and Summary Table of Mean, Standard Deviation, and Sample Size"
author: "J & Richie"
format: html
execute: 
  echo: false
---
```{r setup, include=FALSE}
library(lterdatasampler)
library(tidyverse)
library(janitor)
library(here)
library(tidyr)
library(dplyr)
library(lubridate)
library(usethis)
library(metajam)
```

```{r}
crab_data <- pie_crab %>%
  group_by(site) %>% 
  summarise(mean = round(mean(size, na.rm = TRUE), 2), 
            std = round(sd(size, na.rm = TRUE), 2),
            ss = n())

crab_data <- crab_data %>% 
  rename("avg_carapace_width(mm)" = mean,
         "Standard Deviation" = std,
         "Sample Size" = ss)

ggplot(data = pie_crab, aes(x = latitude, y = size)) +
  geom_point()

crab_data
```

Johnson, D. 2019. Fiddler crab body size in salt marshes from Florida to Massachusetts, USA at PIE and VCR LTER and NOAA NERR sites during summer 2016. ver 1. Environmental Data Initiative. https://doi.org/10.6073/pasta/4c27d2e778d3325d3830a5142e3839bb (Accessed 2021-05-27).

Johnson DS, Crowley C, Longmire K, Nelson J, Williams B, Wittyngham S. The fiddler crab, Minuca pugnax, follows Bergmann’s rule. Ecol Evol. 2019;00:1–9. https://doi.org/10.1002/ece3.5883
